services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: caseirao
      POSTGRES_PASSWORD: caseirao
      POSTGRES_DB: caseirao
    ports:
      - "5432:5432"
    volumes:
      - caseirao_pg:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
volumes:
  caseirao_pg:
